#the docker compose file version
version: "3.8"
# you can run multiple services inside one docker compose file
# define them with their dependencies one after the other
services:
  # service 1 named react-prod
  react-prod:
    # service 1 container name
    container_name: react-prod
    build:
      # the context (working directory) is the current directory
      # change this to the directory containing the dockerfile if in a different place
      context: .
      # the dockerfile to be run
      dockerfile: Dockerfile
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./letsencryptFile:/letsencrypt
      - ./certs:/etc/letsencrypt
    # - ./:/app
    ports:
      - "80:80"
      - "443:443"
  # cerbot:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_cerbot

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./ssl:/letsencrypt
  #     - ${PWD}/certs:/etc/letsencrypt

  # - ./data/nginx:/etc/nginx/conf.d

  # --------------------- build --------------------
  # docker-compose -f "docker-compose.yml" up -d --build
